// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using westcoast_education2.api.Data;

#nullable disable

namespace westcoasteducation2.api.Data.Migrations
{
    [DbContext(typeof(WestCoastEducationContext))]
    [Migration("20230213112537_AddRelation")]
    partial class AddRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("westcoast_education2.api.Models.CourseNameModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("coursesNameData");
                });

            modelBuilder.Entity("westcoast_education2.api.Models.CoursesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("courseNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("endDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("nameId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("placeStudy")
                        .HasColumnType("TEXT");

                    b.Property<string>("startDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("teacher")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("nameId");

                    b.ToTable("coursesData");
                });

            modelBuilder.Entity("westcoast_education2.api.Models.StudentsModel", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("address")
                        .HasColumnType("TEXT");

                    b.Property<int>("coursesTakenId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("firstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("lastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("personNu")
                        .HasColumnType("TEXT");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("userId");

                    b.HasIndex("coursesTakenId");

                    b.ToTable("studentData");
                });

            modelBuilder.Entity("westcoast_education2.api.Models.TeachersModel", b =>
                {
                    b.Property<int>("TUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("address")
                        .HasColumnType("TEXT");

                    b.Property<int>("coursesTaughtId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("firstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("lastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("phoneNumber")
                        .HasColumnType("TEXT");

                    b.HasKey("TUserId");

                    b.HasIndex("coursesTaughtId");

                    b.ToTable("teacherData");
                });

            modelBuilder.Entity("westcoast_education2.api.Models.CoursesModel", b =>
                {
                    b.HasOne("westcoast_education2.api.Models.CourseNameModel", "courseName")
                        .WithMany("Courses")
                        .HasForeignKey("nameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("courseName");
                });

            modelBuilder.Entity("westcoast_education2.api.Models.StudentsModel", b =>
                {
                    b.HasOne("westcoast_education2.api.Models.CourseNameModel", "courseName")
                        .WithMany("StudentsCourses")
                        .HasForeignKey("coursesTakenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("courseName");
                });

            modelBuilder.Entity("westcoast_education2.api.Models.TeachersModel", b =>
                {
                    b.HasOne("westcoast_education2.api.Models.CourseNameModel", "courseName")
                        .WithMany("TeachersCourses")
                        .HasForeignKey("coursesTaughtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("courseName");
                });

            modelBuilder.Entity("westcoast_education2.api.Models.CourseNameModel", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("StudentsCourses");

                    b.Navigation("TeachersCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
